### ISSUE TITLE
Unable to add more than one entity

### ISSUE THREAD

**Issue by KevinHaeusler** [nigl/homeassistant_eta_integration#3]
Hello. I am not 100% sure if it is a homeassistant issue or an integration issue. 

I can only select one entity in the dropdown. After that my entity dropdown list stays empty.

Tried different browsers + adding the integration on my phone.

Is there a way to add the remaining entities manually via config?

**Comment by benjamin-becht** [comment]
Hello,

after installation and inside "add integration", choosing ETA sensors - Step 1 and clicking on send (to Host-IP:Port)
When the dropdown-menu appears then you cannot select anything => just click on **send** once, you receive an error message in red colour; but from here on you can select the dropdown-menu and add many ETA sensors.

Only the name of each sensor show under the ETA sensor package does not resolve - it only shows up as "IP:port" of the ETA heating host system - instead of for example "boiler temperature".

This integration is pretty good so far, hope the creator is fixing the small issues. Really thankful for it so far!

**Comment by nigl** [comment]
@KevinHaeusler @SirkoVZ I don't see this error on my homeassistant installation.
Could you check in your homeassistant logs if there is a n error?

**Comment by SirkoVZ** [comment]
ok, I added it again, and now there is no issue anymore 👍

**Comment by KevinHaeusler** [comment]
Same. Readded the integration and now it works fine.
